pool:
  vmImage: "ubuntu"

stages:
  - stage: GetCertificate
    jobs:
      - job: PrepareCSR
        steps:
          - task: PythonScript@0
            inputs:
              script: pip3 install -r requirements.txt
          - task: PythonScript@0
            inputs:
              script: python3 generate_csr.py > csr.der
            env:
              CSR_COMMON_NAME: $(CSR_COMMON_NAME)
      - job: RunACMEClient
        steps:
          - task: PythonScript@0
            inputs:
              script: python3 acme_tiny.py --private-key private_key.json --regr regr.json --csr csr.der > certificate_chain.pem
              



