pool:
  vmImage: "ubuntu-20.04"

parameters:
  - name: 'FORCE_RENEW_CERT'
    displayName: 'force certificate to be renewed'
    type: boolean
    default: False
    values:
      - False
      - True

stages:
  - stage: GetCertificate
    jobs:
      - job: GetCertificateFromKV
        steps:
          - task: AzureCLI@2
            name: check_expire
            env:
              FORCE_RENEW_CERT: ${{ parameters.FORCE_RENEW_CERT }}
            inputs:
              azureSubscription: $(KEY_VAULT_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                env
                echo $FORCE_RENEW_CERT
                if [[ "${FORCE_RENEW_CERT}" = true ]]
                then
                  echo "force renew certificate"
                  echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
                  exit 0
                fi

                echo "get certificate from keyvault"
                RESULT=$(az keyvault certificate download --vault-name $(KEY_VAULT_NAME) -n $(KEY_VAULT_CERT_NAME) -f certificate.pem)
                if [ $? -eq 0 ]
                then
                  echo "certificate found, test expire date"
                  rm -f certificate.pem
                else
                  echo "certificate not found, create new certificate"
                  echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
                fi

                # if [ $? -eq 0 ]
                # then
                #   echo "certificate found, test expire date"
                #   if openssl x509 -checkend $(CERT_NAME_EXPIRE_SECONDS) -noout -in cert.pem
                #   then
                #     echo "expire date is greater then CERT_NAME_EXPIRE_SECONDS"
                #     echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]False"
                #   else
                #     echo "expire date is less then CERT_NAME_EXPIRE_SECONDS, , create new certificate"
                #     echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
                #   fi
                # else
                #   echo "certificate not found, create new certificate"
                #   echo "##vso[task.setvariable variable=NEW_CERTIFICATE;isOutput=true]True"
                # fi
                # Python to return if expired on timedelta variable
      - job: GetCertificateFromLE
        condition: succeeded()
        dependsOn: GetCertificateFromKV
        variables:
          NEW_CERTIFICATE: $[ dependencies.GetCertificateFromKV.outputs['check_expire.NEW_CERTIFICATE'] ]
        steps:
          - script: pip3 install --require-hashes -r requirements.txt
            name: install_requirements
            condition: and(succeeded(), eq(variables.NEW_CERTIFICATE, true))
          - task: PythonScript@0
            name: generate_csr
            condition: and(succeeded(), eq(variables.NEW_CERTIFICATE, true))
            inputs:
              scriptSource: filePath
              scriptPath: generate_csr.py
              arguments: --common-name $(csr_common_name) --out csr.der --rsa-key-size 2048
          - task: Bash@3
            name: save_keys_to_file
            condition: and(succeeded(), eq(variables.NEW_CERTIFICATE, true))
            env:
              LE_PRIVATE_KEY_JSON: $(LE_PRIVATE_KEY_JSON)
              LE_REGR_JSON: $(LE_REGR_JSON)
            inputs:
              targetType: "inline"
              script: |
                printf "%s\n" $LE_PRIVATE_KEY_JSON > private_key.json
                printf "%s\n" $LE_REGR_JSON > regr.json
          - task: PythonScript@0
            name: acme_tiny
            condition: and(succeeded(), eq(variables.NEW_CERTIFICATE, true))
            env:
              AZURE_TENANT_ID: $(LE_AZURE_TENANT_ID)
              AZURE_SUBSCRIPTION_ID: $(LE_AZURE_SUBSCRIPTION_ID)
              AZURE_CLIENT_ID: $(LE_AZURE_CLIENT_ID)
              AZURE_CLIENT_SECRET: $(LE_AZURE_CLIENT_SECRET)
            inputs:
              scriptSource: filePath
              scriptPath: acme_tiny.py
              arguments: --private-key private_key.json --regr regr.json --csr csr.der --out certificate_chain.pem
          - task: AzureCLI@2
            name: save_cert_keyvault
            condition: and(succeeded(), eq(variables.NEW_CERTIFICATE, true))
            inputs:
              azureSubscription: $(KEY_VAULT_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                cat csr.key >> certificate_chain.pem
                az keyvault certificate import --vault-name $(KEY_VAULT_NAME) -n $(KEY_VAULT_CERT_NAME) --disabled false -f certificate_chain.pem
          - task: Bash@3
            name: clean_up
            condition: succeededOrFailed()
            inputs:
              targetType: "inline"
              script: |
                ls -la
                cat certificate_chain.pem
                rm -f private_key.json
                rm -f regr.json
                rm -f certificate_chain.pem
